### ISSUE TITLE
Decide playing order

### ISSUE THREAD

**Issue by mohdqasim02** [step-9/acquire-corguls#9]
### Playing order

As a player

I want to see **all players**

so that I can know what is the order of playing

### Acceptance criteria:

- [x] Criteria 1
  - Given the game has started
  - When I land on the game page
  - Then everyone should be able to see the first tile each player got in the activity bar 

- [x] Criteria 2
  - Given the game has started
  - When I land on the game page
  - Then everyone should be able to see the tiles placed on the board for each player

- [x] Criteria 3
  - Given the game has started
  - When I land on the game page
  - Then everyone should be able to see all players in playing order

- [x] Criteria 4
  - Given the game has started
  - When I land on the game page
  - Then everyone should be able to identify who is the current player

- [x] Criteria 5
  - Given the game has started
  - When I land on the game page
  - Then I should be able to identify myself separately among the players

**Comment by utsabbera** [comment]
### Tech tasks 
  - refactor routes
  - tags
  - messages should last 5 secs
